[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# If you have a probe setup, uncomment and use `probe-rs-cli`
#runner = "probe-rs-cli run --chip RP2040"
runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
